---

- name: Install required packages
  apt:
    name: 'tinc'
    state: 'present'
    install_recommends: False

- name: Create system group for VPN service
  group:
    name: '{{ tinc_group }}'
    state: 'present'
    system: True

- name: Create system user for VPN service
  user:
    name: '{{ tinc_user }}'
    state: 'present'
    system: True
    comment: 'tinc VPN service'
    home: '{{ tinc_home }}'
    group: '{{ tinc_group }}'
    shell: '/bin/false'
    createhome: False

- name: Set tincd ulimit options
  template:
    src: 'etc/default/tinc.j2'
    dest: '/etc/default/tinc'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart tinc VPN connection' ]

